# authendication credintials
credentials:
  usernames:
    taqia:
      email: taqia@gmail.com
      name: Taqia Ashraf
      password: $2b$12$Vya.5Gw0ur0pDxsjt22/suzsNMS/xXYti30GXZZFQ62nUWwmcLJFm # Placeholder for hashed password of 'abc'

cookie:
  expiry_days: 1
  key: some_signature_key # Must be string
  name: some_cookie_name
preauthorized:
  emails:
  - taqia@gmail.com



db:
  host: "localhost"
  user: "root"
  passwd: "TA63!cse@2019"
  database: "expenseDB"
  auth_plugin: "mysql_native_password"

  
email_sender:
  email: "taqia@gmail.com"
  pass: 'TA1199'